//
//  StyleKitName.m
//  ProjectName
//
//  Created by AuthorName on 5/23/17.
//  Copyright (c) 2017 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitName.h"


@implementation StyleKitName

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.496 green: 0.396 blue: 0.396 alpha: 1];
    UIColor* color2 = [UIColor colorWithRed: 0.761 green: 0.32 blue: 0.8 alpha: 1];

    //// Variable Declarations
    CGFloat expression = 1;

    //// Bezier Drawing
    UIBezierPath* bezierPath = [UIBezierPath bezierPath];
    [bezierPath moveToPoint: CGPointMake(135.5, 72.5)];
    [bezierPath addLineToPoint: CGPointMake(158.5, 85.5)];
    [bezierPath addCurveToPoint: CGPointMake(155.65, 66.98) controlPoint1: CGPointMake(158.5, 85.5) controlPoint2: CGPointMake(157.55, 77.78)];
    [bezierPath moveToPoint: CGPointMake(42.5, 66.5)];
    [bezierPath addCurveToPoint: CGPointMake(119.97, 3.3) controlPoint1: CGPointMake(36.24, 48.29) controlPoint2: CGPointMake(130.75, -6)];
    [bezierPath addCurveToPoint: CGPointMake(110.5, 16.5) controlPoint1: CGPointMake(116.98, 5.88) controlPoint2: CGPointMake(113.83, 10.15)];
    [bezierPath addCurveToPoint: CGPointMake(42.5, 25.5) controlPoint1: CGPointMake(103.3, 30.22) controlPoint2: CGPointMake(46.9, 16.63)];
    [bezierPath moveToPoint: CGPointMake(100.5, 53.5)];
    [bezierPath addCurveToPoint: CGPointMake(100.5, 91.5) controlPoint1: CGPointMake(110.25, 53.5) controlPoint2: CGPointMake(100.5, 91.5)];
    [color setFill];
    [bezierPath fill];
    [color2 setStroke];
    bezierPath.lineWidth = expression;
    [bezierPath stroke];
}

+ (void)drawCanvas2
{

    //// Bezier Drawing
    UIBezierPath* bezierPath = [UIBezierPath bezierPath];
    [bezierPath moveToPoint: CGPointMake(104.5, 202.5)];
    [bezierPath addCurveToPoint: CGPointMake(409.5, 729.5) controlPoint1: CGPointMake(-90.5, 590.5) controlPoint2: CGPointMake(409.5, 720.5)];
    [bezierPath addCurveToPoint: CGPointMake(104.5, 202.5) controlPoint1: CGPointMake(409.5, 738.5) controlPoint2: CGPointMake(299.5, -185.5)];
    [bezierPath closePath];
    [UIColor.grayColor setFill];
    [bezierPath fill];
    [UIColor.blackColor setStroke];
    bezierPath.lineWidth = 1;
    [bezierPath stroke];
}

+ (void)drawCanvas3
{

    //// Bezier Drawing
    UIBezierPath* bezierPath = [UIBezierPath bezierPath];
    [bezierPath moveToPoint: CGPointMake(104.5, 128.98)];
    [bezierPath addCurveToPoint: CGPointMake(409.5, 729.49) controlPoint1: CGPointMake(-90.5, 571.1) controlPoint2: CGPointMake(409.5, 719.24)];
    [bezierPath addCurveToPoint: CGPointMake(104.5, 128.98) controlPoint1: CGPointMake(409.5, 739.75) controlPoint2: CGPointMake(299.5, -313.15)];
    [bezierPath closePath];
    [UIColor.grayColor setFill];
    [bezierPath fill];
    [UIColor.blackColor setStroke];
    bezierPath.lineWidth = 1;
    [bezierPath stroke];
}

@end
